###############################################################################
#                          Docker settings                                    #
###############################################################################
version: '3.9'

services:

    nginx:
        container_name: ${NGINX_SERVER_NAME}
        build: ./docker
        restart: unless-stopped
        working_dir: /application
        volumes:
            - '${NGINX_APPLICATION_VOLUME}:/application'
            - '${NGINX_CONF_FILE}:/etc/nginx/conf.d/default.conf'
            - '${NGINX_LOGS_VOLUME}:/var/log/nginx'
        ports:
            - "${NGINX_EXTERNAL_PORT}:80"
