###############################################################################
#                          Docker settings                                    #
###############################################################################
version: '3.9'

services:

    nginx:
        container_name: ${NGINX_DEVOPS_MONITOR_SERVER_NAME}
        build: ./docker
        restart: unless-stopped
        working_dir: /application
        volumes:
            - '${NGINX_APPLICATION_DEVOPS_MONITOR_VOLUME}:/application'
            - '${NGINX_BUILD_DEVOPS_MONITOR_VOLUME}:/build'
            - '${NGINX_CONF_FILE_DEVOPS_MONITOR}:/etc/nginx/conf.d/default.conf'
            - '${NGINX_LOGS_DEVOPS_MONITOR_VOLUME}:/var/log/nginx'
        ports:
            - "${NGINX_APPLICATION_DEVOPS_MONITOR_EXTERNAL_PORT}:80"
            - "${NGINX_BUILD_DEVOPS_MONITOR_EXTERNAL_PORT}:8080"
        networks:
            - bundle

networks:
    bundle:
      external: true
      name: ${NGINX_NETWORK}
