###############################################################################
#                          Docker settings                                    #
###############################################################################
version: '3.9'

services:

    nginx:
        container_name: ${NGINX_SERVER_NAME}
        build: ./docker
        restart: unless-stopped
        working_dir: /application
        volumes:
            - '${NGINX_APPLICATION_VOLUME_BUNDLE}:/application'
            - '${NGINX_CONF_FILE_BUNDLE}:/etc/nginx/conf.d/default.conf'
            - '${NGINX_LOGS_VOLUME}:/var/log/nginx'
        ports:
            - "${NGINX_EXTERNAL_PORT}:80"
        networks:
            - bundle

networks:
    bundle:
      external: true
      name: ${NGINX_NETWORK}
