###############################################################################
#                          Docker settings                                    #
###############################################################################
version: '3.9'

services:

    nginx:
        container_name: ${NGINX_SERVER_NAME}
        build: ./docker
        restart: unless-stopped
        working_dir: /application
        volumes:
            - './samples:/application'
            - './docker/conf/php-web-bundle.conf:/etc/nginx/conf.d/default.conf'
            - './storage/logs:/var/log/nginx'
        ports:
            - "${NGINX_EXTERNAL_PORT}:80"
        networks:
            - bundle

networks:
    bundle:
      external: true
      name: ${NGINX_NETWORK}
